name: Kuma Reminder

on:
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Send LINE message
        run: |
          curl -X POST https://api.line.me/v2/bot/message/push \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}" \
              -d "{\"to\":\"${{ secrets.LINE_USER_ID }}\",\"messages\":[{\"type\":\"text\",\"text\":\"測試成功！🐻\"}]}"
